DATA1 SEGMENT
NUM1 DB 12H
NUM2 DB 34H
SUM DB 2 DUP (0)
DATA1 ENDS
CODE1 SEGMENT
ASSUME CS: CODE1, DS: DATA1
START: MOV AX, DATA1
MOV DS, AX
MOV CL, 00H
MOV AL, NUM1
ADD AL, NUM2
JNC L1
INC CL
L1: MOV SUM, AH
MOV SUM+1,CL
MOV AL, 4CH
INT 21H
CODE1 ENDS
END START