DATA1 SEGMENT
 SOURCE DB 'HELLO WORLD'
 STRLEN EQU ($-SOURCE) 
               DB 100 DUP()
 DESTINATION DB STRLEN DUP(0)
DATA1 ENDS
CODE1 SEGMENT
 ASSUME CS:CODE1,DS:DATA1,ES:DATA1
  START:MOV AX,DATA1
 MOV DS,AX
 MOV ES,AX
 LEA SI,SOURCE
 LEA DI,DESTINATION
 MOV CX,STRLEN
 CLD
        REP MOVSB
 MOV AH,4CH
 INT 21H
CODE1 ENDS
  END START