DISPLAY MACRO MSG
	MOV AH,09H
	LEA DX,MSG
	INT 21H
	ENDM
DATA SEGMENT
	CR EQU 0DH
	LF EQU 0AH
	MSG1 DB 'ONCE I WAS SEVEN YEARS OLD MY MAMA TOLD ME',LF,CR,'$'
	MSG2 DB 'GO MAKE YOURSELF SOME FRIENDS OR YOU WILL BE LONELY',LF,CR,'$'
	MSG3 DB 'ONCE I WAS SEVEN YEARS OLD$'
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE,DS:DATA
            START:MOV AX,DATA
	MOV DS,AX
	DISPLAY MSG1
	DISPLAY MSG2
  	DISPLAY MSG3
	MOV AH,4CH
	INT 21H
	CODE ENDS
  END START
