DATA1 SEGMENT
 SRC DB 'HELLO WORLD'
 STRLEN EQU ($-SRC) 
               DB 100 DUP()
 DES DB STRLEN DUP(0)
DATA1 ENDS
CODE1 SEGMENT
 ASSUME CS:CODE1,DS:DATA1,ES:DATA1
  START:MOV AX,DATA1
 MOV DS,AX
 MOV ES,AX
 LEA SI,SRC
 LEA DI,DES
 MOV CX,STRLEN
 CLD
        REP MOVSB
 MOV AH,4CH
 INT 21H
CODE1 ENDS
  END START